[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Expertise"
  pageRef = "expertise"
  weight = 20

[[main]]
  name = "Work"
  pageRef = "work"
  weight = 30

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 50

[[footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/sunayanag/"
  weight = 10

[[footer]]
  name = "GitHub"
  url = "https://github.com/sunayana"
  weight = 20

[[footer]]
  name = "ResearchGate"
  url = "https://www.researchgate.net/profile/Sunayana-Ghosh"
  weight = 30

[[footer]]
  name = "Resume"
  url = "/docs/resume-public.pdf"
  weight = 40
